## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.6
  - 0.7
  - nightly
matrix:
  allow_failures:
  - julia: 0.7
  - julia: nightly
notifications:
  email: false
git:
  depth: 99999999

#script: # use the default script which also does a git fetch --unshallow
#  - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.test("Jacobi")'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("Jacobi")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("Jacobi")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
